### ISSUE TITLE
[Demo_vtk-1][ML]Add a function to draw something that I specified.

### ISSUE THREAD

**Issue by HazzaCheng** [wzx140/Demo_vtk#1]
Can you add a function to draw something that I specified?

**Comment by wzx140** [comment]
> Can you add a function to draw something that I specified?

Sorry, your request does not comply with relevant legal requirements.

**Comment by HazzaCheng** [comment]
> > Can you add a function to draw something that I specified?
> 
> Sorry, your request does not comply with relevant legal requirements.

Pardon?

**Comment by wzx140** [comment]
> > > Can you add a function to draw something that I specified?
> > 
> > 
> > Sorry, your request does not comply with relevant legal requirements.
> 
> Pardon?

That means your issue is illegal.

**Comment by HazzaCheng** [comment]
> > > > Can you add a function to draw something that I specified?
> > > 
> > > 
> > > Sorry, your request does not comply with relevant legal requirements.
> > 
> > 
> > Pardon?
> 
> That means your issue is illegal.

I don't think so. I think you must be zhuangbi.
